# Generated by Django 5.2.5 on 2025-09-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StructureInventory',
            fields=[
                ('LotExtID', models.IntegerField()),
                ('LotDesc', models.IntegerField()),
                ('DEExtID', models.IntegerField(primary_key=True, serialize=False)),
                ('DEDesc', models.IntegerField()),
                ('DEType', models.CharField()),
                ('Ftype', models.CharField()),
                ('Ctype', models.CharField()),
                ('Atype', models.CharField()),
                ('StructMin', models.DecimalField(decimal_places=5, max_digits=15)),
                ('StructML', models.DecimalField(decimal_places=5, max_digits=15)),
                ('StructMax', models.DecimalField(decimal_places=5, max_digits=15)),
                ('ContentMin', models.DecimalField(decimal_places=5, max_digits=15)),
                ('ContentML', models.DecimalField(decimal_places=5, max_digits=15)),
                ('ContentMax', models.DecimalField(decimal_places=5, max_digits=15)),
                ('DEWidth', models.FloatField()),
                ('DELength', models.FloatField()),
                ('FFEMin', models.FloatField()),
                ('FFEML', models.FloatField()),
                ('FFEMax', models.FloatField()),
                ('NumOfFloor', models.IntegerField()),
                ('TBuildMin', models.IntegerField()),
                ('TBuildML', models.IntegerField()),
                ('TBuildMax', models.IntegerField()),
                ('BuildNum', models.IntegerField()),
                ('DEActive', models.IntegerField()),
                ('RepPtN', models.FloatField()),
                ('RepPtE', models.FloatField()),
            ],
        ),
    ]
